# Setup taps

tap 'homebrew/core'
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'aws/tap'
tap 'heroku/brew'

# Formulae (In logical groups)

## General
brew 'awscli'
# brew 'aws-sam-cli'  # Upgrade to 1.98.0 caused issues, new set of commands which breaks Steg.AI deployment script.
brew 'direnv'
brew 'dive' # Docker image explorer
brew 'ffmpeg'
brew 'fzf'
brew 'go'
brew 'heroku'
brew 'neovim', args: ["HEAD"]
brew 'node'
brew 'postgresql'
brew 'pnpm'
brew 'python'
brew 'pytorch'
brew 'scipy'
brew 'stow'
brew 'terraform'
brew 'vim'
brew 'yarn'

## Neovim extension dependencies
brew 'gcc'
brew 'lua-language-server'
brew 'ripgrep'
brew 'the_silver_searcher'

## rust/ Neovide dependencies
brew 'rust'
brew 'rustup-init'
brew 'cmake'


# Casks
cask 'adobe-creative-cloud'
cask 'alfred'
cask 'android-sdk'
cask 'android-studio'
cask 'authy'
cask 'bitwarden'
cask 'docker'
cask 'figma'
cask 'fl-studio'
cask 'flux'
cask 'font-fira-code'
cask 'font-jetbrains-mono'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'google-drive'
cask 'java'
cask 'mysqlworkbench'
cask 'neovide'
cask 'nosql-workbench'
cask 'notion'
cask 'obsidian'
cask 'postman'
cask 'react-native-debugger'
cask 'scroll-reverser'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'svgcleaner'
cask 'ticktick'
cask 'iTerm2'
cask 'tunnelblick'
cask 'visual-studio-code'
cask 'zoom'
