# Setup taps

tap 'homebrew/core'
tap 'homebrew/bundle'
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'caskroom/cask'
tap 'heroku/brew'

# Formulae (In logical groups)

## General
brew 'direnv'
# brew 'fish' # After watching Theo from ping.gg's video about how people over do dotfiles, I'm skipping fish as it's unnecessarily complex
brew 'fzf'
brew 'heroku'
brew 'neovim', args: ["HEAD"]
brew 'node'
brew 'postgresql'
brew 'pnpm'
brew 'python'
brew 'vim'
brew 'yarn'

## Neovim extension dependencies
brew 'gcc'
brew 'lua-language-server'
brew 'ripgrep'
brew 'the_silver_searcher'

## rust/ Neovide dependencies
brew 'rust'
brew 'rustup-init'
brew 'cmake'


# Casks
cask 'adobe-creative-cloud'
cask 'alfred'
cask 'android-sdk'
cask 'android-studio'
cask 'authy'
cask 'bitwarden'
cask 'docker'
cask 'figma'
cask 'fl-studio'
cask 'flux'
cask 'font-fira-code'
cask 'font-jetbrains-mono'
cask 'google-chrome'
cask 'google-drive'
cask 'java'
cask 'neovide'
cask 'notion'
cask 'obsidian'
cask 'postman'
cask 'react-native-debugger'
cask 'scroll-reverser'
cask 'slack'
cask 'spectacle'
cask 'spotify'
cask 'svgcleaner'
cask 'iTerm2'
cask 'tunnelblick'
cask 'visual-studio-code'
cask 'zoom'
