return {
    {
        "mason-org/mason-lspconfig.nvim",
        opts = {
            ensure_installed = {
                'angularls',
                'ansiblels',
                'astro',
                'bashls',
                'clangd',
                'cmake',
                'codebook',
                'cssls',
                'docker_language_server',
                'emmet_language_server',
                'eslint',
                'gh_actions_ls',
                'gopls',
                'harper_ls',
                'html',
                'htmx',
                'jdtls',
                'jsonls',
                'kotlin_language_server',
                'lua_ls',
                'marksman',
                'nginx_language_server',
                'postgres_lsp',
                'prismals',
                'ruff',
                'pylsp',
                'sqlls',
                'svelte',
                'tailwindcss',
                'terraformls',
                'ts_ls',
                'vimls',
                'yamlls',
            }
        },
        dependencies = {
            "mason-org/mason.nvim",
            "neovim/nvim-lspconfig",
        },
    }
}
