return {
    {
        'nvim-treesitter/nvim-treesitter',
        config = function(_, opts)
            require('nvim-treesitter').setup(opts)
        end,
        build = ':TSUpdate',
        lazy = false,
        opts = {
            auto_install = true,
            autotag = {
                enable = true,
            },
            ensure_installed = {
                'angular',
                'astro',
                'bash',
                'c',
                'cmake',
                'css',
                'dockerfile',
                'gitignore',
                'go',
                'hjson',
                'html',
                'java',
                'javascript',
                'json',
                'jsonc',
                'jsx',
                'kotlin',
                'latex',
                'lua',
                'markdown',
                'markdown_inline',
                'nginx',
                'objc',
                'prisma',
                'python',
                'rust',
                'scss',
                'sql',
                'svelte',
                'swift',
                'terraform',
                'tsx',
                'typescript',
                'vim',
                'vimdoc',
                'xml',
                'yaml',
                'zsh',
            },
            highlight = {
                enable = true,
                additional_vim_regex_highlighting = false,
            },
            indent = { enabled = true, },
        },
        priority = 9999
    }
}
